spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boards
    username: local
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  jmx:
    enabled: false
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  main:
    lazy-initialization: true
  zipkin:
    enabled: true
    sender.type: web
    base-url: http://localhost:9411
    locator:
      discovery:
        enabled: true
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

eureka:
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
  server:
    expected-client-renewal-interval-seconds: 5

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    circuitbreakers:
      enabled: true
    health:
      show-details: ALWAYS
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      isUserValid_cb:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 20
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 10s
        permmitedNumberOfCallsInHalfOpenState: 5
  bulkhead:
    instances:
      isUserValid_bh:
        maxConcurrentCalls: 20
        maxWaitDuration: 1s
