spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boards
    username: local
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  jmx:
    enabled: false
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  main:
    lazy-initialization: true

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    circuitbreakers:
      enabled: true
    health:
      show-details: ALWAYS
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      isUserValid_cb:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        recordExceptions:
          - feign.FeignException